# Generated by Django 5.0.3 on 2024-03-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admission_numbwe',
            new_name='admission_number',
        ),
    ]
