# Generated by Django 5.0.3 on 2024-03-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0002_rename_admission_numbwe_student_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
