# Generated by Django 5.0.3 on 2024-03-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0004_class_teacher_alter_result_student_student_class_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(related_name='classes', to='resultapp.student'),
        ),
    ]
