# Generated by Django 5.0.3 on 2024-03-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0007_studentuser_teacheruser_remove_class_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacheruser',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
