# Generated by Django 5.0.3 on 2024-03-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0009_delete_studentuser_delete_teacheruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
