# Generated by Django 5.0.3 on 2024-03-24 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0010_teacher_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_obj',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_name',
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultapp.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultapp.class'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultapp.student'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
